services:
  - type: web
    name: ecomml-studio
    env: python
    plan: free
    rootDir: ml
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    healthCheckPath: /healthz
    autoDeploy: true
